/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as AppRouteImport } from './../routes/_app'
import { Route as AdminRouteImport } from './../routes/admin'
import { Route as AuthRouteImport } from './../routes/auth'
import { Route as CheckoutRouteImport } from './../routes/checkout'
import { Route as GuideRouteImport } from './../routes/guide'
import { Route as AppIndexRouteImport } from './../routes/_app.index'
import { Route as AppAccountRouteImport } from './../routes/_app.account'
import { Route as AppBookRouteImport } from './../routes/_app.book'
import { Route as AppDiscoverRouteImport } from './../routes/_app.discover'
import { Route as AppJournalRouteImport } from './../routes/_app.journal'
import { Route as AppTripsRouteImport } from './../routes/_app.trips'
import { Route as AdminAnalyticsRouteImport } from './../routes/admin.analytics'
import { Route as AdminBookingsRouteImport } from './../routes/admin.bookings'
import { Route as AdminCustomersRouteImport } from './../routes/admin.customers'
import { Route as AdminDashboardRouteImport } from './../routes/admin.dashboard'
import { Route as AdminDiscoveriesRouteImport } from './../routes/admin.discoveries'
import { Route as AdminGuidesRouteImport } from './../routes/admin.guides'
import { Route as AdminHarvestRouteImport } from './../routes/admin.harvest'
import { Route as AdminMediaRouteImport } from './../routes/admin.media'
import { Route as AdminPaymentsRouteImport } from './../routes/admin.payments'
import { Route as AdminPlacesRouteImport } from './../routes/admin.places'
import { Route as AdminSettingsRouteImport } from './../routes/admin.settings'
import { Route as AdminStaysRouteImport } from './../routes/admin.stays'
import { Route as AdminTimelineRouteImport } from './../routes/admin.timeline'
import { Route as AdminToursRouteImport } from './../routes/admin.tours'
import { Route as AdminTransfersRouteImport } from './../routes/admin.transfers'
import { Route as AuthCallbackRouteImport } from './../routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './../routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './../routes/auth.login'
import { Route as AuthSignupRouteImport } from './../routes/auth.signup'
import { Route as AuthVerifyRouteImport } from './../routes/auth.verify'
import { Route as CheckoutDetailsRouteImport } from './../routes/checkout.details'
import { Route as CheckoutFailedRouteImport } from './../routes/checkout.failed'
import { Route as CheckoutPaymentRouteImport } from './../routes/checkout.payment'
import { Route as CheckoutProcessingRouteImport } from './../routes/checkout.processing'
import { Route as CheckoutSuccessRouteImport } from './../routes/checkout.success'
import { Route as GuideCheckInRouteImport } from './../routes/guide.check-in'
import { Route as GuideDashboardRouteImport } from './../routes/guide.dashboard'
import { Route as GuideProfileRouteImport } from './../routes/guide.profile'
import { Route as GuideScheduleRouteImport } from './../routes/guide.schedule'
import { Route as AppAccountNotificationsRouteImport } from './../routes/_app.account.notifications'
import { Route as AppAccountPaymentsRouteImport } from './../routes/_app.account.payments'
import { Route as AppAccountPrivacyRouteImport } from './../routes/_app.account.privacy'
import { Route as AppAccountProfileRouteImport } from './../routes/_app.account.profile'
import { Route as AppAccountSavedRouteImport } from './../routes/_app.account.saved'
import { Route as AppAccountSettingsRouteImport } from './../routes/_app.account.settings'
import { Route as AppBookIndexRouteImport } from './../routes/_app.book.index'
import { Route as AppBookCartRouteImport } from './../routes/_app.book.cart'
import { Route as AppBookExperiencesRouteImport } from './../routes/_app.book.experiences'
import { Route as AppBookStaysRouteImport } from './../routes/_app.book.stays'
import { Route as AppBookToursRouteImport } from './../routes/_app.book.tours'
import { Route as AppBookTransfersRouteImport } from './../routes/_app.book.transfers'
import { Route as AppDiscoverIndexRouteImport } from './../routes/_app.discover.index'
import { Route as AppDiscoverMapRouteImport } from './../routes/_app.discover.map'
import { Route as AppDiscoverNearbyRouteImport } from './../routes/_app.discover.nearby'
import { Route as AppDiscoverPlacesRouteImport } from './../routes/_app.discover.places'
import { Route as AppDiscoverRegionsRouteImport } from './../routes/_app.discover.regions'
import { Route as AppDiscoverSearchRouteImport } from './../routes/_app.discover.search'
import { Route as AppJournalIndexRouteImport } from './../routes/_app.journal.index'
import { Route as AppJournalCreateRouteImport } from './../routes/_app.journal.create'
import { Route as AppJournalFeedRouteImport } from './../routes/_app.journal.feed'
import { Route as AppJournalMapRouteImport } from './../routes/_app.journal.map'
import { Route as AppJournalPinRouteImport } from './../routes/_app.journal.pin'
import { Route as AppTripsIndexRouteImport } from './../routes/_app.trips.index'
import { Route as AppTripsBookingIdRouteImport } from './../routes/_app.trips.$bookingId'
import { Route as AppTripsPastRouteImport } from './../routes/_app.trips.past'
import { Route as AppTripsUpcomingRouteImport } from './../routes/_app.trips.upcoming'
import { Route as AdminBookingsBookingIdRouteImport } from './../routes/admin.bookings.$bookingId'
import { Route as AdminCustomersCustomerIdRouteImport } from './../routes/admin.customers.$customerId'
import { Route as AdminHarvestClaimIdRouteImport } from './../routes/admin.harvest.$claimId'
import { Route as AdminHarvestQueueRouteImport } from './../routes/admin.harvest.queue'
import { Route as AdminPlacesPlaceIdRouteImport } from './../routes/admin.places.$placeId'
import { Route as AdminPlacesNewRouteImport } from './../routes/admin.places.new'
import { Route as AdminStaysStayIdRouteImport } from './../routes/admin.stays.$stayId'
import { Route as AdminToursTourIdRouteImport } from './../routes/admin.tours.$tourId'
import { Route as AdminToursNewRouteImport } from './../routes/admin.tours.new'
import { Route as GuideBookingBookingIdRouteImport } from './../routes/guide.booking.$bookingId'
import { Route as GuideTransferBookingIdRouteImport } from './../routes/guide.transfer.$bookingId'
import { Route as AppBookExperiencesIndexRouteImport } from './../routes/_app.book.experiences.index'
import { Route as AppBookExperiencesExperienceSlugRouteImport } from './../routes/_app.book.experiences.$experienceSlug'
import { Route as AppBookStaysIndexRouteImport } from './../routes/_app.book.stays.index'
import { Route as AppBookStaysHotelSlugRouteImport } from './../routes/_app.book.stays.$hotelSlug'
import { Route as AppBookToursIndexRouteImport } from './../routes/_app.book.tours.index'
import { Route as AppBookToursTourSlugRouteImport } from './../routes/_app.book.tours.$tourSlug'
import { Route as AppBookTransfersIndexRouteImport } from './../routes/_app.book.transfers.index'
import { Route as AppBookTransfersTransferSlugRouteImport } from './../routes/_app.book.transfers.$transferSlug'
import { Route as AppDiscoverPlacesIndexRouteImport } from './../routes/_app.discover.places.index'
import { Route as AppDiscoverPlacesPlaceSlugRouteImport } from './../routes/_app.discover.places.$placeSlug'
import { Route as AppDiscoverRegionsRegionSlugRouteImport } from './../routes/_app.discover.regions.$regionSlug'
import { Route as AppJournalPinPinIdRouteImport } from './../routes/_app.journal.pin.$pinId'
import { Route as AppTripsBookingIdItineraryRouteImport } from './../routes/_app.trips.$bookingId.itinerary'
import { Route as AppTripsBookingIdSupportRouteImport } from './../routes/_app.trips.$bookingId.support'
import { Route as AppTripsBookingIdTicketRouteImport } from './../routes/_app.trips.$bookingId.ticket'
import { Route as AppTripsBookingIdTransferRouteImport } from './../routes/_app.trips.$bookingId.transfer'
import { Route as AppDiscoverPlacesPlaceSlugIndexRouteImport } from './../routes/_app.discover.places.$placeSlug.index'
import { Route as AppDiscoverPlacesPlaceSlugDiscoveriesRouteImport } from './../routes/_app.discover.places.$placeSlug.discoveries'
import { Route as AppDiscoverPlacesPlaceSlugExperiencesRouteImport } from './../routes/_app.discover.places.$placeSlug.experiences'
import { Route as AppDiscoverPlacesPlaceSlugMediaRouteImport } from './../routes/_app.discover.places.$placeSlug.media'
import { Route as AppDiscoverPlacesPlaceSlugTimelineRouteImport } from './../routes/_app.discover.places.$placeSlug.timeline'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscoveriesRoute = AdminDiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHarvestRoute = AdminHarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesRoute = AdminPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaysRoute = AdminStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimelineRoute = AdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const CheckoutDetailsRoute = CheckoutDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutProcessingRoute = CheckoutProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const GuideCheckInRoute = GuideCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => GuideRoute,
} as any)
const GuideDashboardRoute = GuideDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuideRoute,
} as any)
const GuideProfileRoute = GuideProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GuideRoute,
} as any)
const GuideScheduleRoute = GuideScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => GuideRoute,
} as any)
const AppAccountNotificationsRoute = AppAccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountPaymentsRoute = AppAccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountPrivacyRoute = AppAccountPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountSavedRoute = AppAccountSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountSettingsRoute = AppAccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppBookIndexRoute = AppBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookRoute,
} as any)
const AppBookCartRoute = AppBookCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppBookRoute,
} as any)
const AppBookExperiencesRoute = AppBookExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AppBookRoute,
} as any)
const AppBookStaysRoute = AppBookStaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => AppBookRoute,
} as any)
const AppBookToursRoute = AppBookToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AppBookRoute,
} as any)
const AppBookTransfersRoute = AppBookTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppBookRoute,
} as any)
const AppDiscoverIndexRoute = AppDiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDiscoverRoute,
} as any)
const AppDiscoverMapRoute = AppDiscoverMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppDiscoverRoute,
} as any)
const AppDiscoverNearbyRoute = AppDiscoverNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AppDiscoverRoute,
} as any)
const AppDiscoverPlacesRoute = AppDiscoverPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppDiscoverRoute,
} as any)
const AppDiscoverRegionsRoute = AppDiscoverRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AppDiscoverRoute,
} as any)
const AppDiscoverSearchRoute = AppDiscoverSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDiscoverRoute,
} as any)
const AppJournalIndexRoute = AppJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppJournalCreateRoute = AppJournalCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppJournalFeedRoute = AppJournalFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppJournalMapRoute = AppJournalMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppJournalPinRoute = AppJournalPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => AppJournalRoute,
} as any)
const AppTripsIndexRoute = AppTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsBookingIdRoute = AppTripsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsPastRoute = AppTripsPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsUpcomingRoute = AppTripsUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppTripsRoute,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminHarvestClaimIdRoute = AdminHarvestClaimIdRouteImport.update({
  id: '/$claimId',
  path: '/$claimId',
  getParentRoute: () => AdminHarvestRoute,
} as any)
const AdminHarvestQueueRoute = AdminHarvestQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminHarvestRoute,
} as any)
const AdminPlacesPlaceIdRoute = AdminPlacesPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => AdminPlacesRoute,
} as any)
const AdminPlacesNewRoute = AdminPlacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPlacesRoute,
} as any)
const AdminStaysStayIdRoute = AdminStaysStayIdRouteImport.update({
  id: '/$stayId',
  path: '/$stayId',
  getParentRoute: () => AdminStaysRoute,
} as any)
const AdminToursTourIdRoute = AdminToursTourIdRouteImport.update({
  id: '/$tourId',
  path: '/$tourId',
  getParentRoute: () => AdminToursRoute,
} as any)
const AdminToursNewRoute = AdminToursNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminToursRoute,
} as any)
const GuideBookingBookingIdRoute = GuideBookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => GuideRoute,
} as any)
const GuideTransferBookingIdRoute = GuideTransferBookingIdRouteImport.update({
  id: '/transfer/$bookingId',
  path: '/transfer/$bookingId',
  getParentRoute: () => GuideRoute,
} as any)
const AppBookExperiencesIndexRoute = AppBookExperiencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookExperiencesRoute,
} as any)
const AppBookExperiencesExperienceSlugRoute =
  AppBookExperiencesExperienceSlugRouteImport.update({
    id: '/$experienceSlug',
    path: '/$experienceSlug',
    getParentRoute: () => AppBookExperiencesRoute,
  } as any)
const AppBookStaysIndexRoute = AppBookStaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookStaysRoute,
} as any)
const AppBookStaysHotelSlugRoute = AppBookStaysHotelSlugRouteImport.update({
  id: '/$hotelSlug',
  path: '/$hotelSlug',
  getParentRoute: () => AppBookStaysRoute,
} as any)
const AppBookToursIndexRoute = AppBookToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookToursRoute,
} as any)
const AppBookToursTourSlugRoute = AppBookToursTourSlugRouteImport.update({
  id: '/$tourSlug',
  path: '/$tourSlug',
  getParentRoute: () => AppBookToursRoute,
} as any)
const AppBookTransfersIndexRoute = AppBookTransfersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookTransfersRoute,
} as any)
const AppBookTransfersTransferSlugRoute =
  AppBookTransfersTransferSlugRouteImport.update({
    id: '/$transferSlug',
    path: '/$transferSlug',
    getParentRoute: () => AppBookTransfersRoute,
  } as any)
const AppDiscoverPlacesIndexRoute = AppDiscoverPlacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDiscoverPlacesRoute,
} as any)
const AppDiscoverPlacesPlaceSlugRoute =
  AppDiscoverPlacesPlaceSlugRouteImport.update({
    id: '/$placeSlug',
    path: '/$placeSlug',
    getParentRoute: () => AppDiscoverPlacesRoute,
  } as any)
const AppDiscoverRegionsRegionSlugRoute =
  AppDiscoverRegionsRegionSlugRouteImport.update({
    id: '/$regionSlug',
    path: '/$regionSlug',
    getParentRoute: () => AppDiscoverRegionsRoute,
  } as any)
const AppJournalPinPinIdRoute = AppJournalPinPinIdRouteImport.update({
  id: '/$pinId',
  path: '/$pinId',
  getParentRoute: () => AppJournalPinRoute,
} as any)
const AppTripsBookingIdItineraryRoute =
  AppTripsBookingIdItineraryRouteImport.update({
    id: '/itinerary',
    path: '/itinerary',
    getParentRoute: () => AppTripsBookingIdRoute,
  } as any)
const AppTripsBookingIdSupportRoute =
  AppTripsBookingIdSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AppTripsBookingIdRoute,
  } as any)
const AppTripsBookingIdTicketRoute = AppTripsBookingIdTicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => AppTripsBookingIdRoute,
} as any)
const AppTripsBookingIdTransferRoute =
  AppTripsBookingIdTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => AppTripsBookingIdRoute,
  } as any)
const AppDiscoverPlacesPlaceSlugIndexRoute =
  AppDiscoverPlacesPlaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDiscoverPlacesPlaceSlugRoute,
  } as any)
const AppDiscoverPlacesPlaceSlugDiscoveriesRoute =
  AppDiscoverPlacesPlaceSlugDiscoveriesRouteImport.update({
    id: '/discoveries',
    path: '/discoveries',
    getParentRoute: () => AppDiscoverPlacesPlaceSlugRoute,
  } as any)
const AppDiscoverPlacesPlaceSlugExperiencesRoute =
  AppDiscoverPlacesPlaceSlugExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => AppDiscoverPlacesPlaceSlugRoute,
  } as any)
const AppDiscoverPlacesPlaceSlugMediaRoute =
  AppDiscoverPlacesPlaceSlugMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AppDiscoverPlacesPlaceSlugRoute,
  } as any)
const AppDiscoverPlacesPlaceSlugTimelineRoute =
  AppDiscoverPlacesPlaceSlugTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AppDiscoverPlacesPlaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/account': typeof AppAccountRouteWithChildren
  '/book': typeof AppBookRouteWithChildren
  '/discover': typeof AppDiscoverRouteWithChildren
  '/journal': typeof AppJournalRouteWithChildren
  '/trips': typeof AppTripsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/harvest': typeof AdminHarvestRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/places': typeof AdminPlacesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stays': typeof AdminStaysRouteWithChildren
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/tours': typeof AdminToursRouteWithChildren
  '/admin/transfers': typeof AdminTransfersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/processing': typeof CheckoutProcessingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guide/check-in': typeof GuideCheckInRoute
  '/guide/dashboard': typeof GuideDashboardRoute
  '/guide/profile': typeof GuideProfileRoute
  '/guide/schedule': typeof GuideScheduleRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/payments': typeof AppAccountPaymentsRoute
  '/account/privacy': typeof AppAccountPrivacyRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/saved': typeof AppAccountSavedRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/book/cart': typeof AppBookCartRoute
  '/book/experiences': typeof AppBookExperiencesRouteWithChildren
  '/book/stays': typeof AppBookStaysRouteWithChildren
  '/book/tours': typeof AppBookToursRouteWithChildren
  '/book/transfers': typeof AppBookTransfersRouteWithChildren
  '/discover/map': typeof AppDiscoverMapRoute
  '/discover/nearby': typeof AppDiscoverNearbyRoute
  '/discover/places': typeof AppDiscoverPlacesRouteWithChildren
  '/discover/regions': typeof AppDiscoverRegionsRouteWithChildren
  '/discover/search': typeof AppDiscoverSearchRoute
  '/journal/create': typeof AppJournalCreateRoute
  '/journal/feed': typeof AppJournalFeedRoute
  '/journal/map': typeof AppJournalMapRoute
  '/journal/pin': typeof AppJournalPinRouteWithChildren
  '/trips/$bookingId': typeof AppTripsBookingIdRouteWithChildren
  '/trips/past': typeof AppTripsPastRoute
  '/trips/upcoming': typeof AppTripsUpcomingRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/harvest/$claimId': typeof AdminHarvestClaimIdRoute
  '/admin/harvest/queue': typeof AdminHarvestQueueRoute
  '/admin/places/$placeId': typeof AdminPlacesPlaceIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/stays/$stayId': typeof AdminStaysStayIdRoute
  '/admin/tours/$tourId': typeof AdminToursTourIdRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/guide/booking/$bookingId': typeof GuideBookingBookingIdRoute
  '/guide/transfer/$bookingId': typeof GuideTransferBookingIdRoute
  '/book/': typeof AppBookIndexRoute
  '/discover/': typeof AppDiscoverIndexRoute
  '/journal/': typeof AppJournalIndexRoute
  '/trips/': typeof AppTripsIndexRoute
  '/book/experiences/$experienceSlug': typeof AppBookExperiencesExperienceSlugRoute
  '/book/stays/$hotelSlug': typeof AppBookStaysHotelSlugRoute
  '/book/tours/$tourSlug': typeof AppBookToursTourSlugRoute
  '/book/transfers/$transferSlug': typeof AppBookTransfersTransferSlugRoute
  '/discover/places/$placeSlug': typeof AppDiscoverPlacesPlaceSlugRouteWithChildren
  '/discover/regions/$regionSlug': typeof AppDiscoverRegionsRegionSlugRoute
  '/journal/pin/$pinId': typeof AppJournalPinPinIdRoute
  '/trips/$bookingId/itinerary': typeof AppTripsBookingIdItineraryRoute
  '/trips/$bookingId/support': typeof AppTripsBookingIdSupportRoute
  '/trips/$bookingId/ticket': typeof AppTripsBookingIdTicketRoute
  '/trips/$bookingId/transfer': typeof AppTripsBookingIdTransferRoute
  '/book/experiences/': typeof AppBookExperiencesIndexRoute
  '/book/stays/': typeof AppBookStaysIndexRoute
  '/book/tours/': typeof AppBookToursIndexRoute
  '/book/transfers/': typeof AppBookTransfersIndexRoute
  '/discover/places/': typeof AppDiscoverPlacesIndexRoute
  '/discover/places/$placeSlug/discoveries': typeof AppDiscoverPlacesPlaceSlugDiscoveriesRoute
  '/discover/places/$placeSlug/experiences': typeof AppDiscoverPlacesPlaceSlugExperiencesRoute
  '/discover/places/$placeSlug/media': typeof AppDiscoverPlacesPlaceSlugMediaRoute
  '/discover/places/$placeSlug/timeline': typeof AppDiscoverPlacesPlaceSlugTimelineRoute
  '/discover/places/$placeSlug/': typeof AppDiscoverPlacesPlaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/account': typeof AppAccountRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/harvest': typeof AdminHarvestRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/places': typeof AdminPlacesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stays': typeof AdminStaysRouteWithChildren
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/tours': typeof AdminToursRouteWithChildren
  '/admin/transfers': typeof AdminTransfersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/processing': typeof CheckoutProcessingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guide/check-in': typeof GuideCheckInRoute
  '/guide/dashboard': typeof GuideDashboardRoute
  '/guide/profile': typeof GuideProfileRoute
  '/guide/schedule': typeof GuideScheduleRoute
  '/': typeof AppIndexRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/payments': typeof AppAccountPaymentsRoute
  '/account/privacy': typeof AppAccountPrivacyRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/saved': typeof AppAccountSavedRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/book/cart': typeof AppBookCartRoute
  '/discover/map': typeof AppDiscoverMapRoute
  '/discover/nearby': typeof AppDiscoverNearbyRoute
  '/discover/regions': typeof AppDiscoverRegionsRouteWithChildren
  '/discover/search': typeof AppDiscoverSearchRoute
  '/journal/create': typeof AppJournalCreateRoute
  '/journal/feed': typeof AppJournalFeedRoute
  '/journal/map': typeof AppJournalMapRoute
  '/journal/pin': typeof AppJournalPinRouteWithChildren
  '/trips/$bookingId': typeof AppTripsBookingIdRouteWithChildren
  '/trips/past': typeof AppTripsPastRoute
  '/trips/upcoming': typeof AppTripsUpcomingRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/harvest/$claimId': typeof AdminHarvestClaimIdRoute
  '/admin/harvest/queue': typeof AdminHarvestQueueRoute
  '/admin/places/$placeId': typeof AdminPlacesPlaceIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/stays/$stayId': typeof AdminStaysStayIdRoute
  '/admin/tours/$tourId': typeof AdminToursTourIdRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/guide/booking/$bookingId': typeof GuideBookingBookingIdRoute
  '/guide/transfer/$bookingId': typeof GuideTransferBookingIdRoute
  '/book': typeof AppBookIndexRoute
  '/discover': typeof AppDiscoverIndexRoute
  '/journal': typeof AppJournalIndexRoute
  '/trips': typeof AppTripsIndexRoute
  '/book/experiences/$experienceSlug': typeof AppBookExperiencesExperienceSlugRoute
  '/book/stays/$hotelSlug': typeof AppBookStaysHotelSlugRoute
  '/book/tours/$tourSlug': typeof AppBookToursTourSlugRoute
  '/book/transfers/$transferSlug': typeof AppBookTransfersTransferSlugRoute
  '/discover/regions/$regionSlug': typeof AppDiscoverRegionsRegionSlugRoute
  '/journal/pin/$pinId': typeof AppJournalPinPinIdRoute
  '/trips/$bookingId/itinerary': typeof AppTripsBookingIdItineraryRoute
  '/trips/$bookingId/support': typeof AppTripsBookingIdSupportRoute
  '/trips/$bookingId/ticket': typeof AppTripsBookingIdTicketRoute
  '/trips/$bookingId/transfer': typeof AppTripsBookingIdTransferRoute
  '/book/experiences': typeof AppBookExperiencesIndexRoute
  '/book/stays': typeof AppBookStaysIndexRoute
  '/book/tours': typeof AppBookToursIndexRoute
  '/book/transfers': typeof AppBookTransfersIndexRoute
  '/discover/places': typeof AppDiscoverPlacesIndexRoute
  '/discover/places/$placeSlug/discoveries': typeof AppDiscoverPlacesPlaceSlugDiscoveriesRoute
  '/discover/places/$placeSlug/experiences': typeof AppDiscoverPlacesPlaceSlugExperiencesRoute
  '/discover/places/$placeSlug/media': typeof AppDiscoverPlacesPlaceSlugMediaRoute
  '/discover/places/$placeSlug/timeline': typeof AppDiscoverPlacesPlaceSlugTimelineRoute
  '/discover/places/$placeSlug': typeof AppDiscoverPlacesPlaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/book': typeof AppBookRouteWithChildren
  '/_app/discover': typeof AppDiscoverRouteWithChildren
  '/_app/journal': typeof AppJournalRouteWithChildren
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discoveries': typeof AdminDiscoveriesRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/harvest': typeof AdminHarvestRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/places': typeof AdminPlacesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stays': typeof AdminStaysRouteWithChildren
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/tours': typeof AdminToursRouteWithChildren
  '/admin/transfers': typeof AdminTransfersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/processing': typeof CheckoutProcessingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guide/check-in': typeof GuideCheckInRoute
  '/guide/dashboard': typeof GuideDashboardRoute
  '/guide/profile': typeof GuideProfileRoute
  '/guide/schedule': typeof GuideScheduleRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/notifications': typeof AppAccountNotificationsRoute
  '/_app/account/payments': typeof AppAccountPaymentsRoute
  '/_app/account/privacy': typeof AppAccountPrivacyRoute
  '/_app/account/profile': typeof AppAccountProfileRoute
  '/_app/account/saved': typeof AppAccountSavedRoute
  '/_app/account/settings': typeof AppAccountSettingsRoute
  '/_app/book/cart': typeof AppBookCartRoute
  '/_app/book/experiences': typeof AppBookExperiencesRouteWithChildren
  '/_app/book/stays': typeof AppBookStaysRouteWithChildren
  '/_app/book/tours': typeof AppBookToursRouteWithChildren
  '/_app/book/transfers': typeof AppBookTransfersRouteWithChildren
  '/_app/discover/map': typeof AppDiscoverMapRoute
  '/_app/discover/nearby': typeof AppDiscoverNearbyRoute
  '/_app/discover/places': typeof AppDiscoverPlacesRouteWithChildren
  '/_app/discover/regions': typeof AppDiscoverRegionsRouteWithChildren
  '/_app/discover/search': typeof AppDiscoverSearchRoute
  '/_app/journal/create': typeof AppJournalCreateRoute
  '/_app/journal/feed': typeof AppJournalFeedRoute
  '/_app/journal/map': typeof AppJournalMapRoute
  '/_app/journal/pin': typeof AppJournalPinRouteWithChildren
  '/_app/trips/$bookingId': typeof AppTripsBookingIdRouteWithChildren
  '/_app/trips/past': typeof AppTripsPastRoute
  '/_app/trips/upcoming': typeof AppTripsUpcomingRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/harvest/$claimId': typeof AdminHarvestClaimIdRoute
  '/admin/harvest/queue': typeof AdminHarvestQueueRoute
  '/admin/places/$placeId': typeof AdminPlacesPlaceIdRoute
  '/admin/places/new': typeof AdminPlacesNewRoute
  '/admin/stays/$stayId': typeof AdminStaysStayIdRoute
  '/admin/tours/$tourId': typeof AdminToursTourIdRoute
  '/admin/tours/new': typeof AdminToursNewRoute
  '/guide/booking/$bookingId': typeof GuideBookingBookingIdRoute
  '/guide/transfer/$bookingId': typeof GuideTransferBookingIdRoute
  '/_app/book/': typeof AppBookIndexRoute
  '/_app/discover/': typeof AppDiscoverIndexRoute
  '/_app/journal/': typeof AppJournalIndexRoute
  '/_app/trips/': typeof AppTripsIndexRoute
  '/_app/book/experiences/$experienceSlug': typeof AppBookExperiencesExperienceSlugRoute
  '/_app/book/stays/$hotelSlug': typeof AppBookStaysHotelSlugRoute
  '/_app/book/tours/$tourSlug': typeof AppBookToursTourSlugRoute
  '/_app/book/transfers/$transferSlug': typeof AppBookTransfersTransferSlugRoute
  '/_app/discover/places/$placeSlug': typeof AppDiscoverPlacesPlaceSlugRouteWithChildren
  '/_app/discover/regions/$regionSlug': typeof AppDiscoverRegionsRegionSlugRoute
  '/_app/journal/pin/$pinId': typeof AppJournalPinPinIdRoute
  '/_app/trips/$bookingId/itinerary': typeof AppTripsBookingIdItineraryRoute
  '/_app/trips/$bookingId/support': typeof AppTripsBookingIdSupportRoute
  '/_app/trips/$bookingId/ticket': typeof AppTripsBookingIdTicketRoute
  '/_app/trips/$bookingId/transfer': typeof AppTripsBookingIdTransferRoute
  '/_app/book/experiences/': typeof AppBookExperiencesIndexRoute
  '/_app/book/stays/': typeof AppBookStaysIndexRoute
  '/_app/book/tours/': typeof AppBookToursIndexRoute
  '/_app/book/transfers/': typeof AppBookTransfersIndexRoute
  '/_app/discover/places/': typeof AppDiscoverPlacesIndexRoute
  '/_app/discover/places/$placeSlug/discoveries': typeof AppDiscoverPlacesPlaceSlugDiscoveriesRoute
  '/_app/discover/places/$placeSlug/experiences': typeof AppDiscoverPlacesPlaceSlugExperiencesRoute
  '/_app/discover/places/$placeSlug/media': typeof AppDiscoverPlacesPlaceSlugMediaRoute
  '/_app/discover/places/$placeSlug/timeline': typeof AppDiscoverPlacesPlaceSlugTimelineRoute
  '/_app/discover/places/$placeSlug/': typeof AppDiscoverPlacesPlaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/guide'
    | '/account'
    | '/book'
    | '/discover'
    | '/journal'
    | '/trips'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/discoveries'
    | '/admin/guides'
    | '/admin/harvest'
    | '/admin/media'
    | '/admin/payments'
    | '/admin/places'
    | '/admin/settings'
    | '/admin/stays'
    | '/admin/timeline'
    | '/admin/tours'
    | '/admin/transfers'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/checkout/details'
    | '/checkout/failed'
    | '/checkout/payment'
    | '/checkout/processing'
    | '/checkout/success'
    | '/guide/check-in'
    | '/guide/dashboard'
    | '/guide/profile'
    | '/guide/schedule'
    | '/account/notifications'
    | '/account/payments'
    | '/account/privacy'
    | '/account/profile'
    | '/account/saved'
    | '/account/settings'
    | '/book/cart'
    | '/book/experiences'
    | '/book/stays'
    | '/book/tours'
    | '/book/transfers'
    | '/discover/map'
    | '/discover/nearby'
    | '/discover/places'
    | '/discover/regions'
    | '/discover/search'
    | '/journal/create'
    | '/journal/feed'
    | '/journal/map'
    | '/journal/pin'
    | '/trips/$bookingId'
    | '/trips/past'
    | '/trips/upcoming'
    | '/admin/bookings/$bookingId'
    | '/admin/customers/$customerId'
    | '/admin/harvest/$claimId'
    | '/admin/harvest/queue'
    | '/admin/places/$placeId'
    | '/admin/places/new'
    | '/admin/stays/$stayId'
    | '/admin/tours/$tourId'
    | '/admin/tours/new'
    | '/guide/booking/$bookingId'
    | '/guide/transfer/$bookingId'
    | '/book/'
    | '/discover/'
    | '/journal/'
    | '/trips/'
    | '/book/experiences/$experienceSlug'
    | '/book/stays/$hotelSlug'
    | '/book/tours/$tourSlug'
    | '/book/transfers/$transferSlug'
    | '/discover/places/$placeSlug'
    | '/discover/regions/$regionSlug'
    | '/journal/pin/$pinId'
    | '/trips/$bookingId/itinerary'
    | '/trips/$bookingId/support'
    | '/trips/$bookingId/ticket'
    | '/trips/$bookingId/transfer'
    | '/book/experiences/'
    | '/book/stays/'
    | '/book/tours/'
    | '/book/transfers/'
    | '/discover/places/'
    | '/discover/places/$placeSlug/discoveries'
    | '/discover/places/$placeSlug/experiences'
    | '/discover/places/$placeSlug/media'
    | '/discover/places/$placeSlug/timeline'
    | '/discover/places/$placeSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/guide'
    | '/account'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/discoveries'
    | '/admin/guides'
    | '/admin/harvest'
    | '/admin/media'
    | '/admin/payments'
    | '/admin/places'
    | '/admin/settings'
    | '/admin/stays'
    | '/admin/timeline'
    | '/admin/tours'
    | '/admin/transfers'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/checkout/details'
    | '/checkout/failed'
    | '/checkout/payment'
    | '/checkout/processing'
    | '/checkout/success'
    | '/guide/check-in'
    | '/guide/dashboard'
    | '/guide/profile'
    | '/guide/schedule'
    | '/'
    | '/account/notifications'
    | '/account/payments'
    | '/account/privacy'
    | '/account/profile'
    | '/account/saved'
    | '/account/settings'
    | '/book/cart'
    | '/discover/map'
    | '/discover/nearby'
    | '/discover/regions'
    | '/discover/search'
    | '/journal/create'
    | '/journal/feed'
    | '/journal/map'
    | '/journal/pin'
    | '/trips/$bookingId'
    | '/trips/past'
    | '/trips/upcoming'
    | '/admin/bookings/$bookingId'
    | '/admin/customers/$customerId'
    | '/admin/harvest/$claimId'
    | '/admin/harvest/queue'
    | '/admin/places/$placeId'
    | '/admin/places/new'
    | '/admin/stays/$stayId'
    | '/admin/tours/$tourId'
    | '/admin/tours/new'
    | '/guide/booking/$bookingId'
    | '/guide/transfer/$bookingId'
    | '/book'
    | '/discover'
    | '/journal'
    | '/trips'
    | '/book/experiences/$experienceSlug'
    | '/book/stays/$hotelSlug'
    | '/book/tours/$tourSlug'
    | '/book/transfers/$transferSlug'
    | '/discover/regions/$regionSlug'
    | '/journal/pin/$pinId'
    | '/trips/$bookingId/itinerary'
    | '/trips/$bookingId/support'
    | '/trips/$bookingId/ticket'
    | '/trips/$bookingId/transfer'
    | '/book/experiences'
    | '/book/stays'
    | '/book/tours'
    | '/book/transfers'
    | '/discover/places'
    | '/discover/places/$placeSlug/discoveries'
    | '/discover/places/$placeSlug/experiences'
    | '/discover/places/$placeSlug/media'
    | '/discover/places/$placeSlug/timeline'
    | '/discover/places/$placeSlug'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/guide'
    | '/_app/account'
    | '/_app/book'
    | '/_app/discover'
    | '/_app/journal'
    | '/_app/trips'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/discoveries'
    | '/admin/guides'
    | '/admin/harvest'
    | '/admin/media'
    | '/admin/payments'
    | '/admin/places'
    | '/admin/settings'
    | '/admin/stays'
    | '/admin/timeline'
    | '/admin/tours'
    | '/admin/transfers'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/checkout/details'
    | '/checkout/failed'
    | '/checkout/payment'
    | '/checkout/processing'
    | '/checkout/success'
    | '/guide/check-in'
    | '/guide/dashboard'
    | '/guide/profile'
    | '/guide/schedule'
    | '/_app/'
    | '/_app/account/notifications'
    | '/_app/account/payments'
    | '/_app/account/privacy'
    | '/_app/account/profile'
    | '/_app/account/saved'
    | '/_app/account/settings'
    | '/_app/book/cart'
    | '/_app/book/experiences'
    | '/_app/book/stays'
    | '/_app/book/tours'
    | '/_app/book/transfers'
    | '/_app/discover/map'
    | '/_app/discover/nearby'
    | '/_app/discover/places'
    | '/_app/discover/regions'
    | '/_app/discover/search'
    | '/_app/journal/create'
    | '/_app/journal/feed'
    | '/_app/journal/map'
    | '/_app/journal/pin'
    | '/_app/trips/$bookingId'
    | '/_app/trips/past'
    | '/_app/trips/upcoming'
    | '/admin/bookings/$bookingId'
    | '/admin/customers/$customerId'
    | '/admin/harvest/$claimId'
    | '/admin/harvest/queue'
    | '/admin/places/$placeId'
    | '/admin/places/new'
    | '/admin/stays/$stayId'
    | '/admin/tours/$tourId'
    | '/admin/tours/new'
    | '/guide/booking/$bookingId'
    | '/guide/transfer/$bookingId'
    | '/_app/book/'
    | '/_app/discover/'
    | '/_app/journal/'
    | '/_app/trips/'
    | '/_app/book/experiences/$experienceSlug'
    | '/_app/book/stays/$hotelSlug'
    | '/_app/book/tours/$tourSlug'
    | '/_app/book/transfers/$transferSlug'
    | '/_app/discover/places/$placeSlug'
    | '/_app/discover/regions/$regionSlug'
    | '/_app/journal/pin/$pinId'
    | '/_app/trips/$bookingId/itinerary'
    | '/_app/trips/$bookingId/support'
    | '/_app/trips/$bookingId/ticket'
    | '/_app/trips/$bookingId/transfer'
    | '/_app/book/experiences/'
    | '/_app/book/stays/'
    | '/_app/book/tours/'
    | '/_app/book/transfers/'
    | '/_app/discover/places/'
    | '/_app/discover/places/$placeSlug/discoveries'
    | '/_app/discover/places/$placeSlug/experiences'
    | '/_app/discover/places/$placeSlug/media'
    | '/_app/discover/places/$placeSlug/timeline'
    | '/_app/discover/places/$placeSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  GuideRoute: typeof GuideRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book': {
      id: '/_app/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discoveries': {
      id: '/admin/discoveries'
      path: '/discoveries'
      fullPath: '/admin/discoveries'
      preLoaderRoute: typeof AdminDiscoveriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/harvest': {
      id: '/admin/harvest'
      path: '/harvest'
      fullPath: '/admin/harvest'
      preLoaderRoute: typeof AdminHarvestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places': {
      id: '/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AdminPlacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stays': {
      id: '/admin/stays'
      path: '/stays'
      fullPath: '/admin/stays'
      preLoaderRoute: typeof AdminStaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timeline': {
      id: '/admin/timeline'
      path: '/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AdminTimelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/checkout/details': {
      id: '/checkout/details'
      path: '/details'
      fullPath: '/checkout/details'
      preLoaderRoute: typeof CheckoutDetailsRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/processing': {
      id: '/checkout/processing'
      path: '/processing'
      fullPath: '/checkout/processing'
      preLoaderRoute: typeof CheckoutProcessingRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/guide/check-in': {
      id: '/guide/check-in'
      path: '/check-in'
      fullPath: '/guide/check-in'
      preLoaderRoute: typeof GuideCheckInRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/dashboard': {
      id: '/guide/dashboard'
      path: '/dashboard'
      fullPath: '/guide/dashboard'
      preLoaderRoute: typeof GuideDashboardRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/profile': {
      id: '/guide/profile'
      path: '/profile'
      fullPath: '/guide/profile'
      preLoaderRoute: typeof GuideProfileRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/schedule': {
      id: '/guide/schedule'
      path: '/schedule'
      fullPath: '/guide/schedule'
      preLoaderRoute: typeof GuideScheduleRouteImport
      parentRoute: typeof GuideRoute
    }
    '/_app/account/notifications': {
      id: '/_app/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AppAccountNotificationsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/payments': {
      id: '/_app/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AppAccountPaymentsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/privacy': {
      id: '/_app/account/privacy'
      path: '/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AppAccountPrivacyRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/profile': {
      id: '/_app/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/saved': {
      id: '/_app/account/saved'
      path: '/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AppAccountSavedRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/settings': {
      id: '/_app/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppAccountSettingsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/book/': {
      id: '/_app/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof AppBookIndexRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/_app/book/cart': {
      id: '/_app/book/cart'
      path: '/cart'
      fullPath: '/book/cart'
      preLoaderRoute: typeof AppBookCartRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/_app/book/experiences': {
      id: '/_app/book/experiences'
      path: '/experiences'
      fullPath: '/book/experiences'
      preLoaderRoute: typeof AppBookExperiencesRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/_app/book/stays': {
      id: '/_app/book/stays'
      path: '/stays'
      fullPath: '/book/stays'
      preLoaderRoute: typeof AppBookStaysRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/_app/book/tours': {
      id: '/_app/book/tours'
      path: '/tours'
      fullPath: '/book/tours'
      preLoaderRoute: typeof AppBookToursRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/_app/book/transfers': {
      id: '/_app/book/transfers'
      path: '/transfers'
      fullPath: '/book/transfers'
      preLoaderRoute: typeof AppBookTransfersRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/_app/discover/': {
      id: '/_app/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof AppDiscoverIndexRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
    '/_app/discover/map': {
      id: '/_app/discover/map'
      path: '/map'
      fullPath: '/discover/map'
      preLoaderRoute: typeof AppDiscoverMapRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
    '/_app/discover/nearby': {
      id: '/_app/discover/nearby'
      path: '/nearby'
      fullPath: '/discover/nearby'
      preLoaderRoute: typeof AppDiscoverNearbyRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
    '/_app/discover/places': {
      id: '/_app/discover/places'
      path: '/places'
      fullPath: '/discover/places'
      preLoaderRoute: typeof AppDiscoverPlacesRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
    '/_app/discover/regions': {
      id: '/_app/discover/regions'
      path: '/regions'
      fullPath: '/discover/regions'
      preLoaderRoute: typeof AppDiscoverRegionsRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
    '/_app/discover/search': {
      id: '/_app/discover/search'
      path: '/search'
      fullPath: '/discover/search'
      preLoaderRoute: typeof AppDiscoverSearchRouteImport
      parentRoute: typeof AppDiscoverRoute
    }
    '/_app/journal/': {
      id: '/_app/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof AppJournalIndexRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/_app/journal/create': {
      id: '/_app/journal/create'
      path: '/create'
      fullPath: '/journal/create'
      preLoaderRoute: typeof AppJournalCreateRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/_app/journal/feed': {
      id: '/_app/journal/feed'
      path: '/feed'
      fullPath: '/journal/feed'
      preLoaderRoute: typeof AppJournalFeedRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/_app/journal/map': {
      id: '/_app/journal/map'
      path: '/map'
      fullPath: '/journal/map'
      preLoaderRoute: typeof AppJournalMapRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/_app/journal/pin': {
      id: '/_app/journal/pin'
      path: '/pin'
      fullPath: '/journal/pin'
      preLoaderRoute: typeof AppJournalPinRouteImport
      parentRoute: typeof AppJournalRoute
    }
    '/_app/trips/': {
      id: '/_app/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AppTripsIndexRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$bookingId': {
      id: '/_app/trips/$bookingId'
      path: '/$bookingId'
      fullPath: '/trips/$bookingId'
      preLoaderRoute: typeof AppTripsBookingIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/past': {
      id: '/_app/trips/past'
      path: '/past'
      fullPath: '/trips/past'
      preLoaderRoute: typeof AppTripsPastRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/upcoming': {
      id: '/_app/trips/upcoming'
      path: '/upcoming'
      fullPath: '/trips/upcoming'
      preLoaderRoute: typeof AppTripsUpcomingRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/harvest/$claimId': {
      id: '/admin/harvest/$claimId'
      path: '/$claimId'
      fullPath: '/admin/harvest/$claimId'
      preLoaderRoute: typeof AdminHarvestClaimIdRouteImport
      parentRoute: typeof AdminHarvestRoute
    }
    '/admin/harvest/queue': {
      id: '/admin/harvest/queue'
      path: '/queue'
      fullPath: '/admin/harvest/queue'
      preLoaderRoute: typeof AdminHarvestQueueRouteImport
      parentRoute: typeof AdminHarvestRoute
    }
    '/admin/places/$placeId': {
      id: '/admin/places/$placeId'
      path: '/$placeId'
      fullPath: '/admin/places/$placeId'
      preLoaderRoute: typeof AdminPlacesPlaceIdRouteImport
      parentRoute: typeof AdminPlacesRoute
    }
    '/admin/places/new': {
      id: '/admin/places/new'
      path: '/new'
      fullPath: '/admin/places/new'
      preLoaderRoute: typeof AdminPlacesNewRouteImport
      parentRoute: typeof AdminPlacesRoute
    }
    '/admin/stays/$stayId': {
      id: '/admin/stays/$stayId'
      path: '/$stayId'
      fullPath: '/admin/stays/$stayId'
      preLoaderRoute: typeof AdminStaysStayIdRouteImport
      parentRoute: typeof AdminStaysRoute
    }
    '/admin/tours/$tourId': {
      id: '/admin/tours/$tourId'
      path: '/$tourId'
      fullPath: '/admin/tours/$tourId'
      preLoaderRoute: typeof AdminToursTourIdRouteImport
      parentRoute: typeof AdminToursRoute
    }
    '/admin/tours/new': {
      id: '/admin/tours/new'
      path: '/new'
      fullPath: '/admin/tours/new'
      preLoaderRoute: typeof AdminToursNewRouteImport
      parentRoute: typeof AdminToursRoute
    }
    '/guide/booking/$bookingId': {
      id: '/guide/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/guide/booking/$bookingId'
      preLoaderRoute: typeof GuideBookingBookingIdRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/transfer/$bookingId': {
      id: '/guide/transfer/$bookingId'
      path: '/transfer/$bookingId'
      fullPath: '/guide/transfer/$bookingId'
      preLoaderRoute: typeof GuideTransferBookingIdRouteImport
      parentRoute: typeof GuideRoute
    }
    '/_app/book/experiences/': {
      id: '/_app/book/experiences/'
      path: '/'
      fullPath: '/book/experiences/'
      preLoaderRoute: typeof AppBookExperiencesIndexRouteImport
      parentRoute: typeof AppBookExperiencesRoute
    }
    '/_app/book/experiences/$experienceSlug': {
      id: '/_app/book/experiences/$experienceSlug'
      path: '/$experienceSlug'
      fullPath: '/book/experiences/$experienceSlug'
      preLoaderRoute: typeof AppBookExperiencesExperienceSlugRouteImport
      parentRoute: typeof AppBookExperiencesRoute
    }
    '/_app/book/stays/': {
      id: '/_app/book/stays/'
      path: '/'
      fullPath: '/book/stays/'
      preLoaderRoute: typeof AppBookStaysIndexRouteImport
      parentRoute: typeof AppBookStaysRoute
    }
    '/_app/book/stays/$hotelSlug': {
      id: '/_app/book/stays/$hotelSlug'
      path: '/$hotelSlug'
      fullPath: '/book/stays/$hotelSlug'
      preLoaderRoute: typeof AppBookStaysHotelSlugRouteImport
      parentRoute: typeof AppBookStaysRoute
    }
    '/_app/book/tours/': {
      id: '/_app/book/tours/'
      path: '/'
      fullPath: '/book/tours/'
      preLoaderRoute: typeof AppBookToursIndexRouteImport
      parentRoute: typeof AppBookToursRoute
    }
    '/_app/book/tours/$tourSlug': {
      id: '/_app/book/tours/$tourSlug'
      path: '/$tourSlug'
      fullPath: '/book/tours/$tourSlug'
      preLoaderRoute: typeof AppBookToursTourSlugRouteImport
      parentRoute: typeof AppBookToursRoute
    }
    '/_app/book/transfers/': {
      id: '/_app/book/transfers/'
      path: '/'
      fullPath: '/book/transfers/'
      preLoaderRoute: typeof AppBookTransfersIndexRouteImport
      parentRoute: typeof AppBookTransfersRoute
    }
    '/_app/book/transfers/$transferSlug': {
      id: '/_app/book/transfers/$transferSlug'
      path: '/$transferSlug'
      fullPath: '/book/transfers/$transferSlug'
      preLoaderRoute: typeof AppBookTransfersTransferSlugRouteImport
      parentRoute: typeof AppBookTransfersRoute
    }
    '/_app/discover/places/': {
      id: '/_app/discover/places/'
      path: '/'
      fullPath: '/discover/places/'
      preLoaderRoute: typeof AppDiscoverPlacesIndexRouteImport
      parentRoute: typeof AppDiscoverPlacesRoute
    }
    '/_app/discover/places/$placeSlug': {
      id: '/_app/discover/places/$placeSlug'
      path: '/$placeSlug'
      fullPath: '/discover/places/$placeSlug'
      preLoaderRoute: typeof AppDiscoverPlacesPlaceSlugRouteImport
      parentRoute: typeof AppDiscoverPlacesRoute
    }
    '/_app/discover/regions/$regionSlug': {
      id: '/_app/discover/regions/$regionSlug'
      path: '/$regionSlug'
      fullPath: '/discover/regions/$regionSlug'
      preLoaderRoute: typeof AppDiscoverRegionsRegionSlugRouteImport
      parentRoute: typeof AppDiscoverRegionsRoute
    }
    '/_app/journal/pin/$pinId': {
      id: '/_app/journal/pin/$pinId'
      path: '/$pinId'
      fullPath: '/journal/pin/$pinId'
      preLoaderRoute: typeof AppJournalPinPinIdRouteImport
      parentRoute: typeof AppJournalPinRoute
    }
    '/_app/trips/$bookingId/itinerary': {
      id: '/_app/trips/$bookingId/itinerary'
      path: '/itinerary'
      fullPath: '/trips/$bookingId/itinerary'
      preLoaderRoute: typeof AppTripsBookingIdItineraryRouteImport
      parentRoute: typeof AppTripsBookingIdRoute
    }
    '/_app/trips/$bookingId/support': {
      id: '/_app/trips/$bookingId/support'
      path: '/support'
      fullPath: '/trips/$bookingId/support'
      preLoaderRoute: typeof AppTripsBookingIdSupportRouteImport
      parentRoute: typeof AppTripsBookingIdRoute
    }
    '/_app/trips/$bookingId/ticket': {
      id: '/_app/trips/$bookingId/ticket'
      path: '/ticket'
      fullPath: '/trips/$bookingId/ticket'
      preLoaderRoute: typeof AppTripsBookingIdTicketRouteImport
      parentRoute: typeof AppTripsBookingIdRoute
    }
    '/_app/trips/$bookingId/transfer': {
      id: '/_app/trips/$bookingId/transfer'
      path: '/transfer'
      fullPath: '/trips/$bookingId/transfer'
      preLoaderRoute: typeof AppTripsBookingIdTransferRouteImport
      parentRoute: typeof AppTripsBookingIdRoute
    }
    '/_app/discover/places/$placeSlug/': {
      id: '/_app/discover/places/$placeSlug/'
      path: '/'
      fullPath: '/discover/places/$placeSlug/'
      preLoaderRoute: typeof AppDiscoverPlacesPlaceSlugIndexRouteImport
      parentRoute: typeof AppDiscoverPlacesPlaceSlugRoute
    }
    '/_app/discover/places/$placeSlug/discoveries': {
      id: '/_app/discover/places/$placeSlug/discoveries'
      path: '/discoveries'
      fullPath: '/discover/places/$placeSlug/discoveries'
      preLoaderRoute: typeof AppDiscoverPlacesPlaceSlugDiscoveriesRouteImport
      parentRoute: typeof AppDiscoverPlacesPlaceSlugRoute
    }
    '/_app/discover/places/$placeSlug/experiences': {
      id: '/_app/discover/places/$placeSlug/experiences'
      path: '/experiences'
      fullPath: '/discover/places/$placeSlug/experiences'
      preLoaderRoute: typeof AppDiscoverPlacesPlaceSlugExperiencesRouteImport
      parentRoute: typeof AppDiscoverPlacesPlaceSlugRoute
    }
    '/_app/discover/places/$placeSlug/media': {
      id: '/_app/discover/places/$placeSlug/media'
      path: '/media'
      fullPath: '/discover/places/$placeSlug/media'
      preLoaderRoute: typeof AppDiscoverPlacesPlaceSlugMediaRouteImport
      parentRoute: typeof AppDiscoverPlacesPlaceSlugRoute
    }
    '/_app/discover/places/$placeSlug/timeline': {
      id: '/_app/discover/places/$placeSlug/timeline'
      path: '/timeline'
      fullPath: '/discover/places/$placeSlug/timeline'
      preLoaderRoute: typeof AppDiscoverPlacesPlaceSlugTimelineRouteImport
      parentRoute: typeof AppDiscoverPlacesPlaceSlugRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountNotificationsRoute: typeof AppAccountNotificationsRoute
  AppAccountPaymentsRoute: typeof AppAccountPaymentsRoute
  AppAccountPrivacyRoute: typeof AppAccountPrivacyRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSavedRoute: typeof AppAccountSavedRoute
  AppAccountSettingsRoute: typeof AppAccountSettingsRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountNotificationsRoute: AppAccountNotificationsRoute,
  AppAccountPaymentsRoute: AppAccountPaymentsRoute,
  AppAccountPrivacyRoute: AppAccountPrivacyRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSavedRoute: AppAccountSavedRoute,
  AppAccountSettingsRoute: AppAccountSettingsRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppBookExperiencesRouteChildren {
  AppBookExperiencesExperienceSlugRoute: typeof AppBookExperiencesExperienceSlugRoute
  AppBookExperiencesIndexRoute: typeof AppBookExperiencesIndexRoute
}

const AppBookExperiencesRouteChildren: AppBookExperiencesRouteChildren = {
  AppBookExperiencesExperienceSlugRoute: AppBookExperiencesExperienceSlugRoute,
  AppBookExperiencesIndexRoute: AppBookExperiencesIndexRoute,
}

const AppBookExperiencesRouteWithChildren =
  AppBookExperiencesRoute._addFileChildren(AppBookExperiencesRouteChildren)

interface AppBookStaysRouteChildren {
  AppBookStaysHotelSlugRoute: typeof AppBookStaysHotelSlugRoute
  AppBookStaysIndexRoute: typeof AppBookStaysIndexRoute
}

const AppBookStaysRouteChildren: AppBookStaysRouteChildren = {
  AppBookStaysHotelSlugRoute: AppBookStaysHotelSlugRoute,
  AppBookStaysIndexRoute: AppBookStaysIndexRoute,
}

const AppBookStaysRouteWithChildren = AppBookStaysRoute._addFileChildren(
  AppBookStaysRouteChildren,
)

interface AppBookToursRouteChildren {
  AppBookToursTourSlugRoute: typeof AppBookToursTourSlugRoute
  AppBookToursIndexRoute: typeof AppBookToursIndexRoute
}

const AppBookToursRouteChildren: AppBookToursRouteChildren = {
  AppBookToursTourSlugRoute: AppBookToursTourSlugRoute,
  AppBookToursIndexRoute: AppBookToursIndexRoute,
}

const AppBookToursRouteWithChildren = AppBookToursRoute._addFileChildren(
  AppBookToursRouteChildren,
)

interface AppBookTransfersRouteChildren {
  AppBookTransfersTransferSlugRoute: typeof AppBookTransfersTransferSlugRoute
  AppBookTransfersIndexRoute: typeof AppBookTransfersIndexRoute
}

const AppBookTransfersRouteChildren: AppBookTransfersRouteChildren = {
  AppBookTransfersTransferSlugRoute: AppBookTransfersTransferSlugRoute,
  AppBookTransfersIndexRoute: AppBookTransfersIndexRoute,
}

const AppBookTransfersRouteWithChildren =
  AppBookTransfersRoute._addFileChildren(AppBookTransfersRouteChildren)

interface AppBookRouteChildren {
  AppBookCartRoute: typeof AppBookCartRoute
  AppBookExperiencesRoute: typeof AppBookExperiencesRouteWithChildren
  AppBookStaysRoute: typeof AppBookStaysRouteWithChildren
  AppBookToursRoute: typeof AppBookToursRouteWithChildren
  AppBookTransfersRoute: typeof AppBookTransfersRouteWithChildren
  AppBookIndexRoute: typeof AppBookIndexRoute
}

const AppBookRouteChildren: AppBookRouteChildren = {
  AppBookCartRoute: AppBookCartRoute,
  AppBookExperiencesRoute: AppBookExperiencesRouteWithChildren,
  AppBookStaysRoute: AppBookStaysRouteWithChildren,
  AppBookToursRoute: AppBookToursRouteWithChildren,
  AppBookTransfersRoute: AppBookTransfersRouteWithChildren,
  AppBookIndexRoute: AppBookIndexRoute,
}

const AppBookRouteWithChildren =
  AppBookRoute._addFileChildren(AppBookRouteChildren)

interface AppDiscoverPlacesPlaceSlugRouteChildren {
  AppDiscoverPlacesPlaceSlugDiscoveriesRoute: typeof AppDiscoverPlacesPlaceSlugDiscoveriesRoute
  AppDiscoverPlacesPlaceSlugExperiencesRoute: typeof AppDiscoverPlacesPlaceSlugExperiencesRoute
  AppDiscoverPlacesPlaceSlugMediaRoute: typeof AppDiscoverPlacesPlaceSlugMediaRoute
  AppDiscoverPlacesPlaceSlugTimelineRoute: typeof AppDiscoverPlacesPlaceSlugTimelineRoute
  AppDiscoverPlacesPlaceSlugIndexRoute: typeof AppDiscoverPlacesPlaceSlugIndexRoute
}

const AppDiscoverPlacesPlaceSlugRouteChildren: AppDiscoverPlacesPlaceSlugRouteChildren =
  {
    AppDiscoverPlacesPlaceSlugDiscoveriesRoute:
      AppDiscoverPlacesPlaceSlugDiscoveriesRoute,
    AppDiscoverPlacesPlaceSlugExperiencesRoute:
      AppDiscoverPlacesPlaceSlugExperiencesRoute,
    AppDiscoverPlacesPlaceSlugMediaRoute: AppDiscoverPlacesPlaceSlugMediaRoute,
    AppDiscoverPlacesPlaceSlugTimelineRoute:
      AppDiscoverPlacesPlaceSlugTimelineRoute,
    AppDiscoverPlacesPlaceSlugIndexRoute: AppDiscoverPlacesPlaceSlugIndexRoute,
  }

const AppDiscoverPlacesPlaceSlugRouteWithChildren =
  AppDiscoverPlacesPlaceSlugRoute._addFileChildren(
    AppDiscoverPlacesPlaceSlugRouteChildren,
  )

interface AppDiscoverPlacesRouteChildren {
  AppDiscoverPlacesPlaceSlugRoute: typeof AppDiscoverPlacesPlaceSlugRouteWithChildren
  AppDiscoverPlacesIndexRoute: typeof AppDiscoverPlacesIndexRoute
}

const AppDiscoverPlacesRouteChildren: AppDiscoverPlacesRouteChildren = {
  AppDiscoverPlacesPlaceSlugRoute: AppDiscoverPlacesPlaceSlugRouteWithChildren,
  AppDiscoverPlacesIndexRoute: AppDiscoverPlacesIndexRoute,
}

const AppDiscoverPlacesRouteWithChildren =
  AppDiscoverPlacesRoute._addFileChildren(AppDiscoverPlacesRouteChildren)

interface AppDiscoverRegionsRouteChildren {
  AppDiscoverRegionsRegionSlugRoute: typeof AppDiscoverRegionsRegionSlugRoute
}

const AppDiscoverRegionsRouteChildren: AppDiscoverRegionsRouteChildren = {
  AppDiscoverRegionsRegionSlugRoute: AppDiscoverRegionsRegionSlugRoute,
}

const AppDiscoverRegionsRouteWithChildren =
  AppDiscoverRegionsRoute._addFileChildren(AppDiscoverRegionsRouteChildren)

interface AppDiscoverRouteChildren {
  AppDiscoverMapRoute: typeof AppDiscoverMapRoute
  AppDiscoverNearbyRoute: typeof AppDiscoverNearbyRoute
  AppDiscoverPlacesRoute: typeof AppDiscoverPlacesRouteWithChildren
  AppDiscoverRegionsRoute: typeof AppDiscoverRegionsRouteWithChildren
  AppDiscoverSearchRoute: typeof AppDiscoverSearchRoute
  AppDiscoverIndexRoute: typeof AppDiscoverIndexRoute
}

const AppDiscoverRouteChildren: AppDiscoverRouteChildren = {
  AppDiscoverMapRoute: AppDiscoverMapRoute,
  AppDiscoverNearbyRoute: AppDiscoverNearbyRoute,
  AppDiscoverPlacesRoute: AppDiscoverPlacesRouteWithChildren,
  AppDiscoverRegionsRoute: AppDiscoverRegionsRouteWithChildren,
  AppDiscoverSearchRoute: AppDiscoverSearchRoute,
  AppDiscoverIndexRoute: AppDiscoverIndexRoute,
}

const AppDiscoverRouteWithChildren = AppDiscoverRoute._addFileChildren(
  AppDiscoverRouteChildren,
)

interface AppJournalPinRouteChildren {
  AppJournalPinPinIdRoute: typeof AppJournalPinPinIdRoute
}

const AppJournalPinRouteChildren: AppJournalPinRouteChildren = {
  AppJournalPinPinIdRoute: AppJournalPinPinIdRoute,
}

const AppJournalPinRouteWithChildren = AppJournalPinRoute._addFileChildren(
  AppJournalPinRouteChildren,
)

interface AppJournalRouteChildren {
  AppJournalCreateRoute: typeof AppJournalCreateRoute
  AppJournalFeedRoute: typeof AppJournalFeedRoute
  AppJournalMapRoute: typeof AppJournalMapRoute
  AppJournalPinRoute: typeof AppJournalPinRouteWithChildren
  AppJournalIndexRoute: typeof AppJournalIndexRoute
}

const AppJournalRouteChildren: AppJournalRouteChildren = {
  AppJournalCreateRoute: AppJournalCreateRoute,
  AppJournalFeedRoute: AppJournalFeedRoute,
  AppJournalMapRoute: AppJournalMapRoute,
  AppJournalPinRoute: AppJournalPinRouteWithChildren,
  AppJournalIndexRoute: AppJournalIndexRoute,
}

const AppJournalRouteWithChildren = AppJournalRoute._addFileChildren(
  AppJournalRouteChildren,
)

interface AppTripsBookingIdRouteChildren {
  AppTripsBookingIdItineraryRoute: typeof AppTripsBookingIdItineraryRoute
  AppTripsBookingIdSupportRoute: typeof AppTripsBookingIdSupportRoute
  AppTripsBookingIdTicketRoute: typeof AppTripsBookingIdTicketRoute
  AppTripsBookingIdTransferRoute: typeof AppTripsBookingIdTransferRoute
}

const AppTripsBookingIdRouteChildren: AppTripsBookingIdRouteChildren = {
  AppTripsBookingIdItineraryRoute: AppTripsBookingIdItineraryRoute,
  AppTripsBookingIdSupportRoute: AppTripsBookingIdSupportRoute,
  AppTripsBookingIdTicketRoute: AppTripsBookingIdTicketRoute,
  AppTripsBookingIdTransferRoute: AppTripsBookingIdTransferRoute,
}

const AppTripsBookingIdRouteWithChildren =
  AppTripsBookingIdRoute._addFileChildren(AppTripsBookingIdRouteChildren)

interface AppTripsRouteChildren {
  AppTripsBookingIdRoute: typeof AppTripsBookingIdRouteWithChildren
  AppTripsPastRoute: typeof AppTripsPastRoute
  AppTripsUpcomingRoute: typeof AppTripsUpcomingRoute
  AppTripsIndexRoute: typeof AppTripsIndexRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsBookingIdRoute: AppTripsBookingIdRouteWithChildren,
  AppTripsPastRoute: AppTripsPastRoute,
  AppTripsUpcomingRoute: AppTripsUpcomingRoute,
  AppTripsIndexRoute: AppTripsIndexRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppBookRoute: typeof AppBookRouteWithChildren
  AppDiscoverRoute: typeof AppDiscoverRouteWithChildren
  AppJournalRoute: typeof AppJournalRouteWithChildren
  AppTripsRoute: typeof AppTripsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppBookRoute: AppBookRouteWithChildren,
  AppDiscoverRoute: AppDiscoverRouteWithChildren,
  AppJournalRoute: AppJournalRouteWithChildren,
  AppTripsRoute: AppTripsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminBookingsRouteChildren {
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminHarvestRouteChildren {
  AdminHarvestClaimIdRoute: typeof AdminHarvestClaimIdRoute
  AdminHarvestQueueRoute: typeof AdminHarvestQueueRoute
}

const AdminHarvestRouteChildren: AdminHarvestRouteChildren = {
  AdminHarvestClaimIdRoute: AdminHarvestClaimIdRoute,
  AdminHarvestQueueRoute: AdminHarvestQueueRoute,
}

const AdminHarvestRouteWithChildren = AdminHarvestRoute._addFileChildren(
  AdminHarvestRouteChildren,
)

interface AdminPlacesRouteChildren {
  AdminPlacesPlaceIdRoute: typeof AdminPlacesPlaceIdRoute
  AdminPlacesNewRoute: typeof AdminPlacesNewRoute
}

const AdminPlacesRouteChildren: AdminPlacesRouteChildren = {
  AdminPlacesPlaceIdRoute: AdminPlacesPlaceIdRoute,
  AdminPlacesNewRoute: AdminPlacesNewRoute,
}

const AdminPlacesRouteWithChildren = AdminPlacesRoute._addFileChildren(
  AdminPlacesRouteChildren,
)

interface AdminStaysRouteChildren {
  AdminStaysStayIdRoute: typeof AdminStaysStayIdRoute
}

const AdminStaysRouteChildren: AdminStaysRouteChildren = {
  AdminStaysStayIdRoute: AdminStaysStayIdRoute,
}

const AdminStaysRouteWithChildren = AdminStaysRoute._addFileChildren(
  AdminStaysRouteChildren,
)

interface AdminToursRouteChildren {
  AdminToursTourIdRoute: typeof AdminToursTourIdRoute
  AdminToursNewRoute: typeof AdminToursNewRoute
}

const AdminToursRouteChildren: AdminToursRouteChildren = {
  AdminToursTourIdRoute: AdminToursTourIdRoute,
  AdminToursNewRoute: AdminToursNewRoute,
}

const AdminToursRouteWithChildren = AdminToursRoute._addFileChildren(
  AdminToursRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiscoveriesRoute: typeof AdminDiscoveriesRoute
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminHarvestRoute: typeof AdminHarvestRouteWithChildren
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlacesRoute: typeof AdminPlacesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaysRoute: typeof AdminStaysRouteWithChildren
  AdminTimelineRoute: typeof AdminTimelineRoute
  AdminToursRoute: typeof AdminToursRouteWithChildren
  AdminTransfersRoute: typeof AdminTransfersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiscoveriesRoute: AdminDiscoveriesRoute,
  AdminGuidesRoute: AdminGuidesRoute,
  AdminHarvestRoute: AdminHarvestRouteWithChildren,
  AdminMediaRoute: AdminMediaRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlacesRoute: AdminPlacesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaysRoute: AdminStaysRouteWithChildren,
  AdminTimelineRoute: AdminTimelineRoute,
  AdminToursRoute: AdminToursRouteWithChildren,
  AdminTransfersRoute: AdminTransfersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CheckoutRouteChildren {
  CheckoutDetailsRoute: typeof CheckoutDetailsRoute
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutProcessingRoute: typeof CheckoutProcessingRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutDetailsRoute: CheckoutDetailsRoute,
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutProcessingRoute: CheckoutProcessingRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface GuideRouteChildren {
  GuideCheckInRoute: typeof GuideCheckInRoute
  GuideDashboardRoute: typeof GuideDashboardRoute
  GuideProfileRoute: typeof GuideProfileRoute
  GuideScheduleRoute: typeof GuideScheduleRoute
  GuideBookingBookingIdRoute: typeof GuideBookingBookingIdRoute
  GuideTransferBookingIdRoute: typeof GuideTransferBookingIdRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideCheckInRoute: GuideCheckInRoute,
  GuideDashboardRoute: GuideDashboardRoute,
  GuideProfileRoute: GuideProfileRoute,
  GuideScheduleRoute: GuideScheduleRoute,
  GuideBookingBookingIdRoute: GuideBookingBookingIdRoute,
  GuideTransferBookingIdRoute: GuideTransferBookingIdRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  GuideRoute: GuideRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
