import { createFileRoute } from '@tanstack/react-router'
import { AdminTransferEditorPage } from '@/modules/admin/pages/AdminMiscPages'

// @ts-ignore — routeTree will be regenerated by tanstackRouter vite plugin
export const Route = createFileRoute('/admin/transfers/$transferId' as never)({
  component: function TransferEditorRoute() {
    const { transferId } = Route.useParams()
    return <AdminTransferEditorPage transferId={transferId} />
  },
})
